# Generated by Django 2.2 on 2020-09-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daolearningapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfStudy', models.CharField(max_length=30)),
                ('wantChazara', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='daflearning1',
            name='indexTypeOfStudy',
        ),
        migrations.RemoveField(
            model_name='daflearning1',
            name='isLearningPage1',
        ),
        migrations.RemoveField(
            model_name='daflearning1',
            name='isLearningPage2',
        ),
        migrations.AlterField(
            model_name='daflearning1',
            name='typeOfStudy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daolearningapp.StudyPlan'),
        ),
    ]
