# Generated by Django 2.2 on 2020-09-24 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daolearningapp', '0002_auto_20200923_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='daflearning1',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daflearning1',
            name='isLearning',
            field=models.BooleanField(default=False),
        ),
    ]
